CREATE USER WebShop1 WITH PASSWORD 'ws1' IN ROLE WebshopRole;
CREATE USER WebShop2 WITH PASSWORD 'ws2' IN ROLE WebshopRole;
CREATE USER Retail1 WITH PASSWORD 're1' IN ROLE RetailerRole;
CREATE USER Retail2 WITH PASSWORD 're2' IN ROLE RetailerRole;
CREATE USER Manufac1 WITH PASSWORD 'ma1' IN ROLE ManufactorerRole;
CREATE USER Manufac2 WITH PASSWORD 'ma2' IN ROLE ManufactorerRole;
CREATE USER WholeSale1 WITH PASSWORD 'ws1' IN ROLE WholeSaleRole;
CREATE USER WholeSale2 WITH PASSWORD 'ws2' IN ROLE WholeSaleRole;
