#!/bin/sh

c:/altera/91/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/ptf_update.pl CPU_System.ptf 

c:/altera/91/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/mk_systembus.pl --sopc_directory=$sopc_builder --sopc_perl=c:/altera/91/quartus//bin/perl --sopc_lib_path="C:/altera/91/quartus/AMVE_TopLevelNew+C:/altera/91/University_Program/components+c:/altera/91/quartus//../ip/altera/sopc_builder_ip+c:/altera/91/quartus//../ip/altera/nios2_ip+c:/altera/91/quartus//sopc_builder/components" --target_module_name=CPU_System --system_directory=C:/altera/91/quartus/AMVE_TopLevelNew --system_name=CPU_System --project_name=AMVE_TopLevel.qpf --sopc_quartus_dir= $1
