# TCL File Generated by Component Editor 9.1
# Mon Nov 15 16:54:55 CET 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | multiplierAdd "multiplierAdd" v1.0
# | null 2010.11.15.16:54:55
# | 
# | 
# | C:/altera/91/quartus/AMVE_TopLevelNew/multiplierAdd.vhd
# | 
# |    ./multiplierAdd.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module multiplierAdd
# | 
set_module_property NAME multiplierAdd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME multiplierAdd
set_module_property TOP_LEVEL_HDL_FILE multiplierAdd.vhd
set_module_property TOP_LEVEL_HDL_MODULE multiplieradd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file multiplierAdd.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2

set_interface_property nios_custom_instruction_slave_0 ENABLED true

add_interface_port nios_custom_instruction_slave_0 dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 datab datab Input 32
add_interface_port nios_custom_instruction_slave_0 result result Output 32
# | 
# +-----------------------------------
