# TCL File Generated by Component Editor 9.1
# Mon Nov 15 20:02:56 CET 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | CodecInterface "CodecInterface" v1.0
# | null 2010.11.15.20:02:56
# | 
# | 
# | C:/altera/91/quartus/AMVE_TopLevelNew/CodecInterface/CodecInterface.vhd
# | 
# |    ./CodecInterface.vhd syn, sim
# |    ./I2CCtrl.vhd syn, sim
# |    ./InitWF8731.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module CodecInterface
# | 
set_module_property NAME CodecInterface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME CodecInterface
set_module_property TOP_LEVEL_HDL_FILE CodecInterface.vhd
set_module_property TOP_LEVEL_HDL_MODULE CodecInterface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file CodecInterface.vhd {SYNTHESIS SIMULATION}
add_file I2CCtrl.vhd {SYNTHESIS SIMULATION}
add_file InitWF8731.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AudioClk12MHz
# | 
add_interface AudioClk12MHz clock end

set_interface_property AudioClk12MHz ENABLED true

add_interface_port AudioClk12MHz csi_AudioClk12MHz_clk clk Input 1
add_interface_port AudioClk12MHz csi_AudioClk12MHz_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AudioOut
# | 
add_interface AudioOut conduit end

set_interface_property AudioOut ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property AudioOut ENABLED true

add_interface_port AudioOut coe_AudioOut_export export Output 24
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Audioin
# | 
add_interface Audioin conduit end

set_interface_property Audioin ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property Audioin ENABLED true

add_interface_port Audioin coe_Audioin_export export Input 24
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AudioSync
# | 
add_interface AudioSync conduit end

set_interface_property AudioSync ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property AudioSync ENABLED true

add_interface_port AudioSync coe_AudioSync_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 associatedClock clockreset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 2
set_interface_property s1 readWaitTime 2
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitStates 1
set_interface_property s1 writeWaitTime 1

set_interface_property s1 ASSOCIATED_CLOCK clockreset
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 4
add_interface_port s1 avs_s1_writedata writedata Input 8
add_interface_port s1 avs_s1_readdata readdata Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecXClk
# | 
add_interface CodecXClk conduit end

set_interface_property CodecXClk ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecXClk ENABLED true

add_interface_port CodecXClk coe_CodecXClk_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecBClk
# | 
add_interface CodecBClk conduit end

set_interface_property CodecBClk ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecBClk ENABLED true

add_interface_port CodecBClk coe_CodecBClk_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecAdcLrc
# | 
add_interface CodecAdcLrc conduit end

set_interface_property CodecAdcLrc ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecAdcLrc ENABLED true

add_interface_port CodecAdcLrc coe_CodecAdcLrc_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecDacLrc
# | 
add_interface CodecDacLrc conduit end

set_interface_property CodecDacLrc ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecDacLrc ENABLED true

add_interface_port CodecDacLrc coe_CodecDacLrc_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecAdcDat
# | 
add_interface CodecAdcDat conduit end

set_interface_property CodecAdcDat ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecAdcDat ENABLED true

add_interface_port CodecAdcDat coe_CodecAdcDat_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecDacDat
# | 
add_interface CodecDacDat conduit end

set_interface_property CodecDacDat ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecDacDat ENABLED true

add_interface_port CodecDacDat coe_CodecDacDat_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecScl
# | 
add_interface CodecScl conduit end

set_interface_property CodecScl ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecScl ENABLED true

add_interface_port CodecScl coe_CodecScl_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point CodecSda
# | 
add_interface CodecSda conduit end

set_interface_property CodecSda ASSOCIATED_CLOCK AudioClk12MHz
set_interface_property CodecSda ENABLED true

add_interface_port CodecSda coe_CodecSda_export export Bidir 1
# | 
# +-----------------------------------
